### ISSUE TITLE
Chrome tests never exit

### ISSUE THREAD

**Issue by t4t5** [mike-north/ember-ci#6]
I'm not sure if I'm misunderstanding something, but after running `ember g travis-chrome`, the tests never exit if I run the `ember test` command.

This also happens in Travis, where, after running all the tests, it says `No output has been received in the last 10m0s`.

Here's what it looks like in a brand new application (running `ember test`):

*Before using the addon (PhantomJS)* (all good):

<img width="605" alt="screen shot 2017-02-13 at 10 15 54" src="https://cloud.githubusercontent.com/assets/2598660/22877367/74f77bea-f1d5-11e6-995b-47d66cc70a6a.png">

*After using the addon (Chrome)* (test hangs after the last "ok"):

<img width="614" alt="screen shot 2017-02-13 at 10 14 54" src="https://cloud.githubusercontent.com/assets/2598660/22877386/82fe975a-f1d5-11e6-831f-4451b298c5ba.png">

**Comment by mike-north** [comment]
I'm not seeing this problem with ember-cli 2.11. Could you please provide the output of 
```
ember version --verbose
```

**Comment by martndemus** [comment]
This is chronic intermittent issue I've been seeing across all travis-ci builds with Chrome.

**Comment by mike-north** [comment]
I have seen chrome hang on travis before, but the screenshots above indicate this can be reproduced locally

**Comment by t4t5** [comment]
That's weird. I use ember-cli 2.11.1, and I tested the command on a brand new app.

Running `ember version --verbose` gives me this:

```
ember-cli: 2.11.1
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
```

**Comment by t4t5** [comment]
Did som more digging, and the problem might actually not be related to this addon.

When I create a brand new app, and simply change `testem.js` to:

```javascript
  "launch_in_ci": [
    "Chrome"
  ],
```

I get the same error. Do you guys think this is an Ember issue? It seems to work well for @mike-north in Ember 2.11 though.

**Comment by t4t5** [comment]
Since it doesn't seem to be an addon problem, I've created an issue on the Ember CLI repo instead that others can follow. Thanks for the quick response! https://github.com/ember-cli/ember-cli/issues/6773
